version: "3.8"

volumes:
  group2:

services:
  group2-database:
    image: postgres:14.4-alpine
    restart: unless-stopped
    container_name: db.group2.com
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      retries: 3
    ports:
      - "7432:5432"
    volumes:
      - group2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: group2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password