version: "3.8"
networks:
  phnompenh:
    driver: bridge
volumes:
  group2:

services:
  group2-database:
    image: postgres:14.4-alpine
    restart: unless-stopped
    container_name: db.group2.com
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      retries: 3
    ports:
      - "7432:5432"
    volumes:
      - group2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: group2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - phnompenh
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: group2-api
    depends_on:
      - group2-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db.group2.com:5432/group2
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - '8080:8080'
    networks:
      - phnompenh