spring:
  application:
    name: demo-application
  datasource:
    url: jdbc:postgresql://localhost:7432/group2
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update

      dialect=org:
        hibernate:
          dialect:
            PostgreSQL9Dialect:show-sql: true

  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
      file-size-threshold: 500MB

  http:
    multipart:
      enabled: 'true'

#server:
#  port: '8090'








  #spring.servlet.multipart.max-file-size=100MB
  #spring.servlet.multipart.max-request-size=100MB
  #spring.http.multipart.enabled=true



