spring:
  application:
    name: demo-application
  datasource:
    url: jdbc:postgresql://localhost:7432/group2
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true